services:
  app:
    build:
      context: .
      dockerfile: App.Dockerfile
    ports:
      - '1738:1738'
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - static:/app/server/static

  db:
    env_file:
      - ./.env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
  static:
